### ISSUE TITLE
Manual Testing Checklist

### ISSUE THREAD

**Issue by yoasyo25** [yoasyo25/overtime-app#13]
### Request Testing Checklist

* [ ] Search, sort, and filter the 'All Requests' page
* [ ] Add new a request
* [ ] Sign in
* [ ] Add tags to a request
* [ ] Change the due date of a request
* [ ] Add and complete tasks for a request
* [ ] Change the POC for a request
* [ ] Add and remove departments for a request
* [ ] Add and remove support staff to a request
* [ ] Change the requester on a request
* [ ] Add internal and external messages to a request
* [ ] Edit a message on a request
* [ ] Add a document to a request
* [ ] Change the visibility of documents on a request
* [ ] Add hours to a request
* [ ] Add an invoice to a request (connect with Stripe form goes to "oops" page)
* [ ] Change the visibility of a request
* [ ] Pause a request
* [ ] Reopen a request
* [ ] Close a request
* [ ] Filter the request timeline
* [ ] Print a request
* [ ] Sign in as a requester
* [ ] As a requester, upload a document
* [ ] As a requester, download a document

### Admin Testing Checklist

* [ ] Sign in as an admin
* [ ] View the dashboard
* [ ] Add, edit, and deactivate a department
* [ ] Add, edit, and deactivate a user
* [ ] Add, edit, and deactivate an alert
* [ ] Add, edit, and deactivate a template
* [ ] Add, edit, and deactivate a redaction reason/patterns
* [ ] Add, edit, and deactivate a tag
* [ ] Change the basic information
* [ ] Change the logo and background image
* [ ] Change the front page text
* [ ] Change the all requests page text
* [ ] Change the custom footer
* [ ] Add an FAQ page
* [ ] Change the due dates
* [ ] Change anticipated fulfillment date
* [ ] Change notifications
* [ ] Change the privacy settings
* [ ] Change the request publishing/visibility
* [ ] Change requester form
* [ ] Change payments option
* [ ] Bulk upload users
* [ ] Bulk upload requests 
* [ ] Change retention policy
* [ ] Change the retention period
* [ ] Add an out-of-office backup
* [ ] Add a permanent backup

### Reports Testing Checklist

* [ ] View the reports page
* [ ] Run the users list report
* [ ] Run the invoicing and payments report
* [ ] Run the time tracking report
* [ ] Run a new report on the 'All Requests' page
* [ ] Run a saved report on the 'All Requests' page

### Documents Testing Checklist

* [ ] Search, filter, and sort the all documents page
* [ ] Upload a document on the all documents page
* [ ] View an individual document
* [ ] Edit info on a single document 
* [ ] Delete an individual document
* [ ] Redact a document
* [ ] Save a redacted document
* [ ] Download redacted document
* [ ] Batch redact documents using the document review tool
* [ ] Create a zip file using the document review tool
* [ ] Release a document
* [ ] Place a document in a folder

### Users Testing Checklist

* [ ] Sign in
* [ ] View user settings
* [ ] Change email preferences

### Customers Page Testing Checklist
* [ ] Can view, sort, filter customers listing 
* [ ] Can change subscription type 
* [ ] Can change account status  

### DemoData (Onboarding)
* [ ] New user can see demodata (users, requests, documents, departments, users, alerts, tags, templates, and messages)
* [ ] New user can delete all requests on requests page
* [ ] New user can delete all demo data
* [ ] New user can change account state to live by clicking Go Live button

### Invite a User
* [ ] An admin can invite a user 
* [ ] A user can successfully sign in using the link from their email 

### Two Factor 
* [ ] Can enable 2FA for a portal 
* [ ] User is asked to enter 6 digit code 
* [ ] User recieves email with 2FA code 
* [ ] User is able to sign in with 2FA code
