### ISSUE TITLE
Document Testing Checklist

### ISSUE THREAD

**Issue by yoasyo25** [yoasyo25/overtime-app#14]
### Documents Testing Checklist

* [ ] Search, filter, and sort the all documents page
* [ ] Upload a document on the all documents page
* [ ] View an individual document
* [ ] Edit info on a single document 
* [ ] Delete an individual document
* [ ] Redact a document
* [ ] Save a redacted document
* [ ] Download redacted document
* [ ] Batch redact documents using the document review tool
* [ ] Create a zip file using the document review tool
* [ ] Release a document
* [ ] Place a document in a folder
