### ISSUE TITLE
Request Testing Checklist (part 2)

### ISSUE THREAD

**Issue by yoasyo25** [yoasyo25/overtime-app#19]
### Request Testing Checklist

* [ ] Add a document to a request
* [ ] Change the visibility of documents on a request
* [ ] Add hours to a request
* [ ] Add an invoice to a request (connect with Stripe form goes to "oops" page)
* [ ] Change the visibility of a request
* [ ] Pause a request
* [ ] Reopen a request
* [ ] Close a request
* [ ] Filter the request timeline
* [ ] Print a request
* [ ] Sign in as a requester
* [ ] As a requester, upload a document
* [ ] As a requester, download a document
