### ISSUE TITLE
Admin Testing Checklist

### ISSUE THREAD

**Issue by yoasyo25** [yoasyo25/overtime-app#20]
### Admin Testing Checklist

* [ ] Sign in as an admin
* [ ] View the dashboard
* [ ] Add, edit, and deactivate a department
* [ ] Add, edit, and deactivate a user
* [ ] Add, edit, and deactivate an alert
* [ ] Add, edit, and deactivate a template
* [ ] Add, edit, and deactivate a redaction reason/patterns
* [ ] Add, edit, and deactivate a tag
* [ ] Change the basic information
* [ ] Change the logo and background image
* [ ] Change the front page text
* [ ] Change the all requests page text
* [ ] Change the custom footer
* [ ] Add an FAQ page
* [ ] Change the due dates
* [ ] Change anticipated fulfillment date
* [ ] Change notifications
* [ ] Change the privacy settings
* [ ] Change the request publishing/visibility
* [ ] Change requester form
* [ ] Change payments option
* [ ] Bulk upload users
* [ ] Bulk upload requests 
* [ ] Change retention policy
* [ ] Change the retention period
* [ ] Add an out-of-office backup
~~* [ ] Add a permanent backup~~
